services:
  palworld:
    image: mbround18/palworld-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      PRESET: "Normal"
      SERVER_PASSWORD: "secure-password"
      ADMIN_PASSWORD: "super-secret-password"
    ports:
      - "8211:8211"
      - "27015:27015"
    volumes:
      - ./tmp:/home/steam/palworld
